### PR TITLE
Plugin options host

### PR DESCRIPTION
**Pull request by Bazze**
Hello 👋 

We just encountered a scenario where we needed to override the host. I did some smaller additions to add "host" to the plugin options. What do you think? 😊 

Let me know if you want me to do some further adjustments.

Thanks

### CODE REVIEW

**Comment by felixheck** [comment]
Hey @Bazze,

thanks for using and contributing to this project, highly appreciated!

Changes lgtm, will be merged in a few minutes as a new minor 😊 
stay safe!

**Comment by Bazze** [comment]
Thanks for creating it! 😉

⭐  to you for being super fast on merging & releasing!

**Comment by felixheck** [comment]
😊 

Honestly, I haven't used it in 3 years and even thought about dropping it.
So it's great to see folks like you @ DPOrganizer who've been with bissle for quite some time now! Thanks a ton for all your contributions in the last years, @Bazze 🤗

Would you be interested in joining the repo as a collaborator? 😊

**Comment by Bazze** [comment]
Oh, I see! Yes, we would gladly join as collaborators since we are indeed using it and want it to be maintained! 😊  

Let me know if there is anything other than the guidelines in CONTRIBUTING.md you want me/us to know!

**Comment by felixheck** [comment]
Welcome on board! 👋 

There's not much you need to know.
Feel free to treat bissle as your own project. Keep acting in the best interests of the project, as you have already proven 😊 

Let me know if there's anybody else @ DPOrganizer who would benefit from joining the project 😊

**Comment by Bazze** [comment]
🎉 

Cool! Sounds good 😊  Will let you know in case, otherwise we proxy the changes through me!

Cheerio!

**Pull request merged**
